### ISSUE TITLE
Update to API 6

### ISSUE THREAD

**Issue by yololetsplay** [Nentify/PlayerShops#5]
Hey there,

API 6.0 is out now, could u please update the plugin?
I get the following exception if I try to buy something ingame.

```
[15:02:09] [Server thread/ERROR] [Sponge/]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=playershops, name=Player Shops, source=/home/servers/sponge_mc/mods/PlayerShops-1.10.2-1.1.1.jar}
java.lang.NoSuchMethodError: net.minecraft.inventory.IInventory.getSizeInventory()I
	at me.nentify.playershops.utils.ChestUtils.hasQuantityOfItems(ChestUtils.java:49) ~[ChestUtils.class:?]
	at me.nentify.playershops.events.BlockEventHandler.onBlockInteract(BlockEventHandler.java:178) ~[BlockEventHandler.class:?]
	at org.spongepowered.common.event.listener.MainHandListener_BlockEventHandler_onBlockInteract58.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:366) [SpongeCommonEventFactory.class:1.10.2-2123-6.0.0-BETA-1880]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:356) [SpongeCommonEventFactory.class:1.10.2-2123-6.0.0-BETA-1880]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:128) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zgp000(NetHandlerPlayServer.java:522) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:125) [PacketUtil.class:1.10.2-2123-6.0.0-BETA-1880]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

I hope u can help me.
I use the latest spongeforge version 1880 and ur plugin version 1.1.0.

Greetz,
yololetsplay

**Comment by Nentify** [comment]
Hi

I don't have much time to develop this plugin at the moment. I tried updating it for the latest API changes yesterday but struggled to find much meaningful documentation/help with the data API changes, sorry.

If someone else updates the plugin, I will happily pull request and do an official release as soon as possible.

**Comment by maxanier** [comment]
Fork: https://github.com/maxanier/PlayerShops
Forum post with changelogs and download links: https://forums.spongepowered.org/t/player-shops-v1-0-0-buy-and-sell-items-to-and-from-other-players/14373/55

@Nentify Feel free to merge my changes into you repo and release official builds. Alternatively you could link this post in the main post for now.
