### ISSUE TITLE
Unable to create player shops on sponge API 5

### ISSUE THREAD

**Issue by AlexxSeven** [Nentify/PlayerShops#6]
Issue with creating shops of any kind with MC 1.10.2 and sponge API 5

Minecraft: 1.10.2
SpongeAPI: 5.1.0-SNAPSHOT-6bcf7eb
SpongeForge: 1.10.2-2123-5.1.0-BETA-1925
Minecraft Forge: 12.18.2.2151

Plugin Version: PlayerShops-1.10.2-1.0.0

Below is the console output i get after running the command, and placing the sign.

`30.11 09:26:51 [Server] Server thread/INFO [nucleus]: _AlexxSeven_ ran the command: /shop sell 1 1
30.11 09:26:52 [Server] Server thread/ERROR [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=playershops, name=Player Shops, version=1.10.2-1.0.0, description=Allows players to create shops, source=/mods/PlayerShops-1.10.2-1.0.0.jar}
30.11 09:26:52 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class me.nentify.playershops.data.PlayerShopKeys
30.11 09:26:52 [Server] INFO at me.nentify.playershops.data.PlayerShopData.quantity(PlayerShopData.java:49) ~[PlayerShopData.class:?]
30.11 09:26:52 [Server] INFO at me.nentify.playershops.events.BlockEventHandler.onBlockPlace(BlockEventHandler.java:61) ~[BlockEventHandler.class:?]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace52.handle(Unknown Source) ~[?:?]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583) ~[TrackingUtil.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503) ~[TrackingUtil.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$36(PacketFunction.java:767) ~[PacketFunction.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$39(PacketFunction.java:765) ~[PacketFunction.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:141) [PacketUtil.class:1.10.2-2123-5.1.0-BETA-1925]
30.11 09:26:52 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
30.11 09:26:52 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
30.11 09:26:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
30.11 09:26:52 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
30.11 09:26:52 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
30.11 09:26:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
30.11 09:26:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
30.11 09:26:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
30.11 09:26:52 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
30.11 09:26:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by maxanier** [comment]
This is an issue with API 5.1 as far as I can tell.
Should be fixed in my fork: https://github.com/maxanier/PlayerShops/commit/46d5ddf3388536dc376c538870289ec630f7353c
Releases: https://forums.spongepowered.org/t/player-shops-v1-0-0-buy-and-sell-items-to-and-from-other-players/14373/55
